language: csharp
mono: none
dotnet: 
  - 2.1.503

cache:
  directories:
    - $HOME/.nuget/packages

#--------- TEST MATRIX --------------
os:
  - linux
  - osx
  - windows

script:
 - ./build.sh
#-----------------------------------

#--------- DEPLOYMENT --------------
jobs: 
  include:
    - stage: deploy
      script:
        - echo "DEPLOYING PROJECT"
      os: linux
#-----------------------------------