language: generic

jobs:
  include:
  - stage: setup files
    script: echo one | tee > ~/$TRAVIS_BUILD_NUMBER/one
  - stage: setup files
    script: echo two | tee > ~/$TRAVIS_BUILD_NUMBER/two
  - stage: use shared files
    script:
    - cat ~/$TRAVIS_BUILD_NUMBER/*
 
addons:
  artifacts:
    s3_region: ap-south-1
    
env:
  global:
  - secure: QkP04MTlxVQaoVIqoosgca4WlRm2JQ9bmLOMKauRe1vaJO5U5GfFCDeR8t4kuCK/ttob4odnA7tC6Fwl/QJC+/K1Tom6NECL44E6EDubvXYynZXx+K2IYj4Txiliw8KAJJf8iKQTFUMkL4wT94d6Y9/5r4i4ZSwXxEFi+aYK9ayzMtY/m2jMaE3PjJpGjRT24/t7/LqBhSTpU+7kYKjSYT598gzXl3DOfyVWtxH+TugNZ18+/d4fkeE3dWYILKXO5IzrOh+WjPt3OCYtMSi5eOnjYIep090Zp9UJV2Qeoaeaqfm3cVL/NJ+qvMAZ//ycLaMhlK1dEqDz5fGoybMtolcnsHg/OK4ZtTwN7UZ6XaPPyZhChhdCwlGVSvOV7zAl4YIpl1HLi7QIUb+sJAuGOu9tuONW4pbgPlY1Dq+wWmjRVvH6d3ReBSGnxgE6mYIKEFdhH85m6TekXsovi4WjGdS+x3DE0CjeIs6CJKQMTO7pPCuBx+YmAvbB2aLtizBdPXnY+8NYhTycE5sNubmDlBik4sTTIKMTZuZ0rJIzs8PtTPAyFgOe1Gs8ckiv8HJE+I570w4QN35EVMD6XsvwaMk3JLbLPKzap616sS3R1tYB2bO9J+9jUdxW+wj3BjtEhClCziKcGR5/xPV0apBtrea5raxfA/pyIiRyw50wiAg=
  - secure: kD8PD7ZaPMlZRwC6Ra7DZHzymgTZPcYO1rLJAVid6GydzobO4FALbsd/ThoGatWUMirSDXeScpVRtwx6w0Ce7x+N5xfjTi2AV5XPNxnhraZK6ZbEiy5br5wFz+BVYQ2MbFQrMNKTFfWNjVsnXiGazj0b0sMyqsvFNkQqCH0L7/cWsp6oSkuf49dFU8H5AnUFPQYuf3zm9TkDlcFabOrWbQALuAqV0zz47osMMWcsRrVvgwfnsvbcePHh0LvJCoFSCGzQA6RvMFjJJI7FpaPbhcouV4ltAmzY9xSM+wCe9jFIJFyiHCb5MxXR9QpupcOpXXLKD9uQ5pEGWMHSJSeH7G14liLzU7C3of3OfYLZKu6RGu4Jk3Y3sjiRlfiPiMJ8ejQp1IimCMSeYZCMS4RutnzwXeZFo/Cp8sNMR/Rfrlgdg/7CKusUmwp0FcJHuqyCWsPOlZf8e6aqR/y8wb8Vcuey+1Ca0rIP8NwhKYKl6FfQiLStQDfi43yICa58YJ5jte/ZANtouzBix7tEFS4sXDBPHQBUWyROHS+2OpW4A7zhcwFrexZB5z+s0ByRMI5mbAyajk9/WX8qbsw+Z3O4j4FGbPlUt/9DtS3lU1DLCk8cAiYcnZ2ZTSHK6umDUtyBpEWsHWiQpVvVuoT8A1nVVTjswePQQ91Woq8u4YcGB5k=
  - secure: LqNcTI/NBSmrG9mUv/H7ej8jzTVYSZmskcbD03VyeCJI7vgEv7LanbCmnHDVTDyLkPS3/Vo45Zx8YpwZrsVOOaYEvvVs7R4dQfivgzadEZzt6ozhzT0MEOXU7SAnnv1rX7yry1egz3EXaNu8QDhL35pyaab6UpdtiG5ZcqOyAVLqAUO8Y17XQzawbygMJglHSvCQoLuEl50hFqqEyhBMQL6Rz/leazMe/Yi1ygSJ/GNzzOmg1snrw2llwdT6/aGMTyLUUhmUkf7YmqwNl4UHcJNa70QIMT+cH6zl9kTa9uabLcnKE9XM8jM8pPRHy+Ejs8HNT/amZ1+wxSbwLYxnz/I1NMDF14op0u/JhYNh9EIWZ7AhEqQVlAkuCcogtvemiqkQ55p2415grHtQlM0IPgJ2G0QhyaPzDVgLq75Cjv334gi7NUe8SD905zRbYHT2WzjD5Kdv3idI1wUAg9s0ZLeNL3nuZU6ET9UHf8Bs/85zFaV9+9vtHk5PJ7/qLH66d/2juplyO0MZeTfJgzJWw2oo63rj9aeDlXnNOgfyBknupi8lTxHVqYNKtZjFrMjwjzAC+48f4Kg3IVQ04vC/uujbQjdwCtophOGu5aXfrCm6f3342HsvRqWHwsvFmxMddSye9aNRBVhFsH7PH28WUNgQN4AoKcFglBUCo4kuj+I=
