language: csharp
mono: none

cache:
  directories:
    - $HOME/.nuget/packages

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

#--------- TEST MATRIX --------------
os:
  - linux
  - osx
  - windows

dotnet: 
  - 2.2

script:
 - ./build.sh
#-----------------------------------

#--------- DEPLOYMENT --------------
jobs: 
  include:
    - stage: deploy
      script:
        - echo "DEPLOYING PROJECT"
      os: linux
#-----------------------------------