language: csharp
mono: none
dotnet: 2.2

cache:
  directories:
    - $HOME/.nuget/packages

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

#--------- TEST MATRIX --------------
os:
  - linux
  - osx
  - windows

script:
 - ./build.sh
#-----------------------------------

#--------- DEPLOYMENT --------------
stages:
  - name: deploy
  
jobs: 
  include:
    - stage: deploy
      script:
        - echo "DEPLOYING PROJECT"
      os: linux
#-----------------------------------