language: csharp
mono: none

cache:
  directories:
    - $HOME/.nuget/packages

#--------- TEST MATRIX --------------
matrix:
  include:
    - name: test on macos using dotnet 2.1.300
      os: osx
      dotnet: 2.1.300
    - name: test on linux using dotnet 2.1
      os: linux
      dotnet: 2.1
    - name: windows test
      os: windows
      dotnet: 2.1

script:
  - if [[ $TRAVIS_OS_NAME == 'windows' ]]; then tbuild.bat; else ./build.sh; fi
#-----------------------------------

#--------- DEPLOYMENT --------------
jobs: 
  include:
    - stage: deploy
      script:
        - echo "DEPLOYING PROJECT"
      os: linux
#-----------------------------------