language: csharp
mono: none

stages:
  - name: test
  - name: deploy
    if: tag IS present

#--------- TEST JOBS --------------
jobs:
  include:
    - stage: test
      name: test on macos using dotnet 2.1.300
      os: osx
      script: dotnet test CommandDotNet.Tests/CommandDotNet.Tests.csproj
      dotnet: 2.1.300
    - name: test on linux using dotnet 2.1
      os: linux
      script: dotnet test CommandDotNet.Tests/CommandDotNet.Tests.csproj
      dotnet: 2.1
    - name: test on windows
      os: windows
      script: dotnet test
#-----------------------------------
  
#--------- DEPLOYMENT JOB ----------  
    - stage: deploy
      name: nuget & github release
      script: ./deploy.sh
      os: linux
      dotnet: 2.1
#-----------------------------------

# cache:
#   directories:
#     - $HOME/.nuget/packages  
