language: csharp
mono: none

#--------- TEST MATRIX --------------
matrix:
  include:
    - name: test on macos using dotnet 2.1.300
      os: osx
      dotnet: 2.1.300
    - name: test on linux using dotnet 2.1
      os: linux
      dotnet: 2.1
    - name: test on windows
      os: windows

script:
  - dotnet test CommandDotNet.Example/CommandDotNet.Example.csproj
#-----------------------------------

#--------- DEPLOYMENT --------------
deploy:
  provider: script
  script: ./deploy.sh
  tags: true
#-----------------------------------

cache:
  directories:
    - $HOME/.nuget/packages  