language: csharp
# mono: none
# dotnet: 2.1

cache:
  directories:
    - $HOME/.nuget/packages

#--------- TEST MATRIX --------------
os:
  - linux
  - osx
  - windows

matrix:
  include:
    - os: linux
      dotnet: 2.1
      env: CONFIG=LINUX_DOTNET-2.1
      mono: none
    - os: osx
      dotnet: 2.1.300
      env: CONFIG=OSX_DOTNET-2.1.300
      mono: none
    # - os: windows
    #   dotnet: 2.1
    #   env: CONFIG=WINDOWS_DOTNET-2.1

script:
  - ./build.sh
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build.sh ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then tbuilt.bat ; fi

#-----------------------------------

#--------- DEPLOYMENT --------------
jobs: 
  include:
    - stage: deploy
      script:
        - echo "DEPLOYING PROJECT"
      os: linux
#-----------------------------------